// <auto-generated />
using System;
using Desicon.Workflow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desicon.Workflow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260809103143_AddAttachments")]
    partial class AddAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desicon.Workflow.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<long>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditEventId"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("EventHash")
                        .IsRequired()
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FromState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OnBehalfOfUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PreviousHash")
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditEventId");

                    b.HasIndex("RequestId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_AuditEvent_Idempotency")
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Notifications.OutboxMessage", b =>
                {
                    b.Property<long>("OutboxMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OutboxMessageId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientRolesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OutboxMessageId");

                    b.HasIndex("RequestId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Outbox_Pending");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.People.Beneficiary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("BankDetailsSetAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("BankDetailsSetByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Beneficiaries", null, t =>
                        {
                            t.HasCheckConstraint("CK_Beneficiary_EmployeeLink", "([Type] <> 'Employee' OR [EmployeeId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.People.Delegation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FromEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ToEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromEmployeeId");

                    b.HasIndex("ToEmployeeId");

                    b.HasIndex("IsActive", "FromEmployeeId", "StartsAt", "EndsAt")
                        .HasDatabaseName("IX_Delegation_Active_From");

                    b.ToTable("Delegations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Delegation_Window", "([EndsAt] >= [StartsAt])");
                        });
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.People.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("DepartmentHeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Department_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Department_Active");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.People.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DefaultCostCentreCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LineManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StaffNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Employee_EntraObjectId");

                    b.HasIndex("LineManagerId")
                        .HasDatabaseName("IX_Employee_LineManager");

                    b.HasIndex("StaffNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Employee_StaffNumber");

                    b.HasIndex("DepartmentId", "IsActive")
                        .HasDatabaseName("IX_Employee_Department_Active");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.AdvanceLine", b =>
                {
                    b.Property<Guid>("LineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("FxRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateOnly>("FxRateDate")
                        .HasColumnType("date");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LineId");

                    b.HasIndex("RequestId");

                    b.ToTable("AdvanceLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_Currency_AdvanceLine", "([CurrencyCode] <> 'NGN' OR [FxRate] = 1.0)");
                        });
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.AdvanceRetirementLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountAppliedNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CashAdvanceRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExpenseRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CashAdvanceRequestId")
                        .HasDatabaseName("IX_AdvanceRetirementLink_CashAdvanceRequest");

                    b.HasIndex("ExpenseRequestId")
                        .IsUnique()
                        .HasDatabaseName("UQ_AdvanceRetirementLink_ExpenseRequest");

                    b.ToTable("AdvanceRetirementLinks", (string)null);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.Attachment", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AttachmentId");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IX_Attachment_Request");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.ExpenseLine", b =>
                {
                    b.Property<Guid>("LineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CostCentreCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ExpenseCategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<decimal>("FxRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateOnly>("FxRateDate")
                        .HasColumnType("date");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LineId");

                    b.HasIndex("RequestId");

                    b.ToTable("ExpenseLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_Currency_ExpenseLine", "([CurrencyCode] <> 'NGN' OR [FxRate] = 1.0)");

                            t.HasCheckConstraint("CK_ExpenseLine_Allocation", "(([ProjectCode] IS NOT NULL AND [CostCentreCode] IS NULL) OR ([ProjectCode] IS NULL AND [CostCentreCode] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.GlPostingLine", b =>
                {
                    b.Property<Guid>("PostingLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("AmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Narration")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PostingLineId");

                    b.HasIndex("RequestId");

                    b.ToTable("GlPostingLines", (string)null);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.Request", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("int");

                    b.Property<string>("BcDocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurrentActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("EscalationCount")
                        .HasColumnType("int");

                    b.Property<string>("FormCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FormRevision")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("JournalVoucherNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("int");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("SlaDueAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StateEnteredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TreasuryNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestId");

                    b.HasIndex("BcDocumentNumber")
                        .HasDatabaseName("IX_Request_BcDocumentNumber")
                        .HasFilter("[BcDocumentNumber] IS NOT NULL");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_RequestNumber");

                    b.HasIndex("RequesterId");

                    b.HasIndex("SlaDueAt")
                        .HasDatabaseName("IX_Request_Sla_Breach")
                        .HasFilter("[ClosedAt] IS NULL");

                    b.HasIndex("CurrentActorId", "CurrentState")
                        .HasDatabaseName("IX_Request_Actor_State");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CurrentActorId", "CurrentState"), new[] { "RequestNumber", "SlaDueAt", "TotalAmountNgn" });

                    b.HasIndex("ModuleKey", "CurrentState", "SubmittedAt")
                        .HasDatabaseName("IX_Request_Ageing");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ModuleKey", "CurrentState", "SubmittedAt"), new[] { "TotalAmountNgn", "DepartmentId" });

                    b.ToTable("Requests", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Security.SecurityEvent", b =>
                {
                    b.Property<long>("SecurityEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SecurityEventId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("AttemptedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FromState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OnBehalfOfUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SecurityEventId");

                    b.HasIndex("AttemptedByUserId", "OccurredAtUtc")
                        .HasDatabaseName("IX_SecurityEvent_Actor");

                    b.HasIndex("RequestId", "OccurredAtUtc")
                        .HasDatabaseName("IX_SecurityEvent_Request");

                    b.ToTable("SecurityEvents", (string)null);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.CashAdvanceRequest", b =>
                {
                    b.HasBaseType("Desicon.Workflow.Domain.Requests.Request");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllocationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AmountInWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AuthorisedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CashReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CostCentreCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("HasSupportingDocuments")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<Guid?>("PostedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RetiredAmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RetirementDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RetirementStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StationScope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("RetirementStatus", "RetirementDueDate")
                        .HasDatabaseName("IX_Advance_Overdue");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("RetirementStatus", "RetirementDueDate"), new[] { "RetiredAmountNgn" });

                    b.ToTable("CashAdvanceRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_Advance_Allocation", "(([AllocationType] = 'Project' AND [ProjectCode] IS NOT NULL) OR ([AllocationType] = 'CostCentre' AND [CostCentreCode] IS NOT NULL))");

                            t.HasCheckConstraint("CK_MakerChecker_Advance", "([PostedByUserId] IS NULL OR [AuthorisedByUserId] IS NULL OR [PostedByUserId] <> [AuthorisedByUserId])");

                            t.HasCheckConstraint("CK_RetirementDue", "([RetirementDueDate] IS NULL OR ([CashReleasedAt] IS NOT NULL AND [RetirementDueDate] >= [CashReleasedAt]))");
                        });
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.ExpenseRequest", b =>
                {
                    b.HasBaseType("Desicon.Workflow.Domain.Requests.Request");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdvanceAmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmountInWords")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("AuthorisedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BeneficiaryBankDetailsSetByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BeneficiaryHasBankDetails")
                        .HasColumnType("bit");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PostedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiptStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("RefundReceivedAmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RetiresAdvanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("RetiresAdvanceId");

                    b.ToTable("ExpenseRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_MakerChecker_Expense", "([PostedByUserId] IS NULL OR [AuthorisedByUserId] IS NULL OR [PostedByUserId] <> [AuthorisedByUserId])");
                        });
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Audit.AuditEvent", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Notifications.OutboxMessage", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.People.Beneficiary", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.People.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.People.Delegation", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.People.Employee", null)
                        .WithMany()
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Desicon.Workflow.Domain.People.Employee", null)
                        .WithMany()
                        .HasForeignKey("ToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.People.Employee", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.People.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Desicon.Workflow.Domain.People.Employee", null)
                        .WithMany()
                        .HasForeignKey("LineManagerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.AdvanceLine", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.CashAdvanceRequest", null)
                        .WithMany("Lines")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.AdvanceRetirementLink", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("CashAdvanceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Desicon.Workflow.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("ExpenseRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.Attachment", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.ExpenseLine", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.ExpenseRequest", null)
                        .WithMany("Lines")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.GlPostingLine", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.Request", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.People.Employee", null)
                        .WithMany()
                        .HasForeignKey("CurrentActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Desicon.Workflow.Domain.People.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Desicon.Workflow.Domain.People.Employee", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.CashAdvanceRequest", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.Request", null)
                        .WithOne()
                        .HasForeignKey("Desicon.Workflow.Domain.Requests.CashAdvanceRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.ExpenseRequest", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.People.Beneficiary", null)
                        .WithMany()
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Desicon.Workflow.Domain.Requests.Request", null)
                        .WithOne()
                        .HasForeignKey("Desicon.Workflow.Domain.Requests.ExpenseRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Desicon.Workflow.Domain.Requests.CashAdvanceRequest", null)
                        .WithMany()
                        .HasForeignKey("RetiresAdvanceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.CashAdvanceRequest", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.ExpenseRequest", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
