// <auto-generated />
using System;
using Desicon.Workflow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desicon.Workflow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260731213220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desicon.Workflow.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<long>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditEventId"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("EventHash")
                        .IsRequired()
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FromState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OnBehalfOfUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PreviousHash")
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditEventId");

                    b.HasIndex("RequestId");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.AdvanceLine", b =>
                {
                    b.Property<Guid>("LineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("FxRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateOnly>("FxRateDate")
                        .HasColumnType("date");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LineId");

                    b.HasIndex("RequestId");

                    b.ToTable("AdvanceLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_Currency_AdvanceLine", "([CurrencyCode] <> 'NGN' OR [FxRate] = 1.0)");
                        });
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.ExpenseLine", b =>
                {
                    b.Property<Guid>("LineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CostCentreCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ExpenseCategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<decimal>("FxRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateOnly>("FxRateDate")
                        .HasColumnType("date");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LineId");

                    b.HasIndex("RequestId");

                    b.ToTable("ExpenseLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_Currency_ExpenseLine", "([CurrencyCode] <> 'NGN' OR [FxRate] = 1.0)");

                            t.HasCheckConstraint("CK_ExpenseLine_Allocation", "(([ProjectCode] IS NOT NULL AND [CostCentreCode] IS NULL) OR ([ProjectCode] IS NULL AND [CostCentreCode] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.GlPostingLine", b =>
                {
                    b.Property<Guid>("PostingLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("AmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Narration")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PostingLineId");

                    b.HasIndex("RequestId");

                    b.ToTable("GlPostingLines", (string)null);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.Request", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurrentActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("EscalationCount")
                        .HasColumnType("int");

                    b.Property<string>("FormCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FormRevision")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("JournalVoucherNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("int");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("SlaDueAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StateEnteredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TreasuryNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestId");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_RequestNumber");

                    b.HasIndex("SlaDueAt")
                        .HasDatabaseName("IX_Request_Sla_Breach")
                        .HasFilter("[ClosedAt] IS NULL");

                    b.HasIndex("CurrentActorId", "CurrentState")
                        .HasDatabaseName("IX_Request_Actor_State");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CurrentActorId", "CurrentState"), new[] { "RequestNumber", "SlaDueAt", "TotalAmountNgn" });

                    b.HasIndex("ModuleKey", "CurrentState", "SubmittedAt")
                        .HasDatabaseName("IX_Request_Ageing");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ModuleKey", "CurrentState", "SubmittedAt"), new[] { "TotalAmountNgn", "DepartmentId" });

                    b.ToTable("Requests", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.CashAdvanceRequest", b =>
                {
                    b.HasBaseType("Desicon.Workflow.Domain.Requests.Request");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllocationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AmountInWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AuthorisedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CashReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CostCentreCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("HasSupportingDocuments")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PostedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RetiredAmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RetirementDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RetirementStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StationScope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("RetirementStatus", "RetirementDueDate")
                        .HasDatabaseName("IX_Advance_Overdue");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("RetirementStatus", "RetirementDueDate"), new[] { "RetiredAmountNgn" });

                    b.ToTable("CashAdvanceRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_Advance_Allocation", "(([AllocationType] = 'Project' AND [ProjectCode] IS NOT NULL) OR ([AllocationType] = 'CostCentre' AND [CostCentreCode] IS NOT NULL))");

                            t.HasCheckConstraint("CK_MakerChecker_Advance", "([PostedByUserId] IS NULL OR [AuthorisedByUserId] IS NULL OR [PostedByUserId] <> [AuthorisedByUserId])");

                            t.HasCheckConstraint("CK_RetirementDue", "([RetirementDueDate] IS NULL OR ([CashReleasedAt] IS NOT NULL AND [RetirementDueDate] >= [CashReleasedAt]))");
                        });
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.ExpenseRequest", b =>
                {
                    b.HasBaseType("Desicon.Workflow.Domain.Requests.Request");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdvanceAmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AmountInWords")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("AuthorisedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeneficiaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PostedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiptStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("RefundReceivedAmountNgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RetiresAdvanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("RetiresAdvanceId");

                    b.ToTable("ExpenseRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_MakerChecker_Expense", "([PostedByUserId] IS NULL OR [AuthorisedByUserId] IS NULL OR [PostedByUserId] <> [AuthorisedByUserId])");
                        });
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Audit.AuditEvent", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.AdvanceLine", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.CashAdvanceRequest", null)
                        .WithMany("Lines")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.ExpenseLine", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.ExpenseRequest", null)
                        .WithMany("Lines")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.GlPostingLine", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.CashAdvanceRequest", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.Request", null)
                        .WithOne()
                        .HasForeignKey("Desicon.Workflow.Domain.Requests.CashAdvanceRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.ExpenseRequest", b =>
                {
                    b.HasOne("Desicon.Workflow.Domain.Requests.Request", null)
                        .WithOne()
                        .HasForeignKey("Desicon.Workflow.Domain.Requests.ExpenseRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Desicon.Workflow.Domain.Requests.CashAdvanceRequest", null)
                        .WithMany()
                        .HasForeignKey("RetiresAdvanceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.CashAdvanceRequest", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Desicon.Workflow.Domain.Requests.ExpenseRequest", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
